#permalink: 
permalink: /content/:year/:month/:day/:title.html
name: Dear Cast & Crew
markdown: redcarpet
highlighter: true

# gems: ['jekyll/itafroma/post_groups']

#pagination: true
#paginate: 24

custom_paginate: 24

# post_groups:
#     - key: author
#       key_plural: authors

# categories:
#   - reviews
#   - streaming
#   - features
 
lunr_search:
  excludes: [rss.xml, atom.xml]


sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "Rakefile"
        - "Gemfile"
        - "Gemfile.lock"
        - "README.md"
        - "s3_website.yml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

jekyll_ga:
  service_account_email: 821215216920-pv14re1k4v8d42l20ssgkqlhreod7m5k@developer.gserviceaccount.com 
  key_file: e1b673f867420911f20306bda171945af21e7a33-privatekey.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID: ga:59905121        # profile ID 
  start: last month         # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: true                # Sort posts by this metric

prose:
  rooturl: '_posts'
  siteurl: 'http://dcac.github.io/'
  media: '/img/article'  
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "review"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "imdb"
        field:
          element: "text"
          label: "IMDB"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "addressee"
        field:
          element: "text"
          label: "Addressee"
          value: ""
      - name: "position"
        field:
          element: "text"
          label: "Position"
          value: ""
      - name: "number"
        field:
          element: "text"
          label: "Stars"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: ""
      - name: "exerpt"
        field:
          element: "textarea"
          label: "Exerpt"
          value: ""
