baseurl: http://dcac.github.io/
permalink: pretty
name: Dear Cast & Crew
markdown: redcarpet
pygments: true

prose:
  rooturl: '_posts'
  siteurl: 'http://dcac.github.io/'
  media: '/img/article'  
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "review"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "addressee"
        field:
          element: "text"
          label: "Addressee"
          value: ""
      - name: "position"
        field:
          element: "text"
          label: "Position"
          value: ""
      - name: "status"
        field:
          element: "text"
          label: "Status"
          value: ""
      - name: "stars"
        field:
          element: "text"
          label: "Stars"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: ""
      - name: "exerpt"
        field:
          element: "textarea"
          label: "Exerpt"
          value: ""
