name: Your New Jekyll Site
markdown: redcarpet
pygments: true


prose:
  rooturl: '_posts'
  siteurl: 'http://dcac.github.io/'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "hidden"
          value: "review"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "addressee"
        field:
          element: "text"
          label: "Addressee"
          value: ""
      - name: "status"
        field:
          element: "text"
          label: "Status"
          value: ""
	  - name: "exerpt"
        field:
          element: "text"
          label: "Exerpt"
          value: ""
 	  - name: "position"
        field:
          element: "text"
          label: "Position"
          value: ""