#permalink: 
permalink: /content/:year/:i_month/:i_day/:title.html
name: Dear Cast & Crew
markdown: redcarpet
highlighter: true
baseurl: www.dearcastandcrew.com

#RSS info
name: Dear Cast & Crew
description: Open letter film reviews, essays, and exchanges.
url: www.dearcastandcrew.com

# gems: ['jekyll/itafroma/post_groups']

#pagination: true
#paginate: 24

exclude: [s3_website.yml, bower_components, README.md, scss, less, js, Gemfile, Gemfile.lock, config.rb, config.codekit, bower.json, css, vendor]

custom_paginate: 24
author_paginate: 24

lunr_search:
  excludes: [rss.xml, atom.xml,feed.xml]

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      section: Content
      layout: review
      grid-display: true
      stars: false
      addressee: false
      comments: true
      split_name: true
      home-display: true
      title-display: true
      share-display: standard
      custom-header: false

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "Rakefile"
        - "Gemfile"
        - "Gemfile.lock"
        - "README.md"
        - "s3_website.yml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

jekyll_ga:
  service_account_email: 821215216920-pv14re1k4v8d42l20ssgkqlhreod7m5k@developer.gserviceaccount.com 
  key_file: e1b673f867420911f20306bda171945af21e7a33-privatekey.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID: ga:59905121        # profile ID 
  start: last month         # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: true                # Sort posts by this metric

prose:
 rooturl: '_posts'
 siteurl: 'http://dcac.github.io/'
 media: '/assets/img/posts/main'  
 metadata:
   _posts:
     - name: "layout"
       field:
         element: "select"
         label: "Layout"
         options:
         - name: "Review"
           value: "review"
         - name: "Essay"
           value: "essay"
     - name: "title"
       field:
         element: "text"
         label: "Title"
     - name: "imdb"
       field:
         element: "text"
         label: "IMDB"
     - name: "author"
       field:
         element: "text"
         label: "Author"
     - name: "addressee"
       field:
         element: "text"
         label: "Addressee"
     - name: "position"
       field:
         element: "text"
         label: "Position"
     - name: "image"
       field:
         element: "text"
         label: "Image"
     - name: "excerpt"
       field:
         element: "textarea"
         label: "Excerpt"
     - name: "stars"
       field:
         element: "number"
         label: "Star Rating"
         type: "number"
         value: "0"
     - name: "tags"
       field:
         element: "multiselect"
         label: "Tags"
         options:
           - name:"Test"
            value:"test"
         alterable: true
