baseurl: http://dcac.github.io/
permalink: pretty
name: Dear Cast & Crew
markdown: redcarpet
pygments: true


=======

prose:
  rooturl: '_posts'
  siteurl: 'http://dcac.github.io/'
  media: '/img/article'  
  metadata:
    _posts:
      - name: "exerpt"
        field:
          element: "textarea"
          label: "Exerpt"
          value: ""
